name: Publish to Github Pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run npm install
        run: npm install
      - name: "Dioxus Deploy"
        uses: DioxusLabs/deploy-action@0.1.2