name: Publish to Github Pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - name: List files in the repository
        run: ls -la
      - name: Run npm install
        run: npm install
      - name: "Dioxus Deploy"
        uses: DioxusLabs/deploy-action@0.1.2